# CMake generated Testfile for 
# Source directory: C:/Users/mreit/src/leaves
# Build directory: C:/Users/mreit/src/leaves
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_mmap "C:/Users/mreit/src/leaves/Debug/test_mmap.exe")
  set_tests_properties(test_mmap PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_mmap "C:/Users/mreit/src/leaves/Release/test_mmap.exe")
  set_tests_properties(test_mmap PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_mmap "C:/Users/mreit/src/leaves/MinSizeRel/test_mmap.exe")
  set_tests_properties(test_mmap PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_mmap "C:/Users/mreit/src/leaves/RelWithDebInfo/test_mmap.exe")
  set_tests_properties(test_mmap PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_mmap NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_fstore "C:/Users/mreit/src/leaves/Debug/test_fstore.exe")
  set_tests_properties(test_fstore PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_fstore "C:/Users/mreit/src/leaves/Release/test_fstore.exe")
  set_tests_properties(test_fstore PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_fstore "C:/Users/mreit/src/leaves/MinSizeRel/test_fstore.exe")
  set_tests_properties(test_fstore PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_fstore "C:/Users/mreit/src/leaves/RelWithDebInfo/test_fstore.exe")
  set_tests_properties(test_fstore PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_fstore NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_memory "C:/Users/mreit/src/leaves/Debug/test_memory.exe")
  set_tests_properties(test_memory PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_memory "C:/Users/mreit/src/leaves/Release/test_memory.exe")
  set_tests_properties(test_memory PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_memory "C:/Users/mreit/src/leaves/MinSizeRel/test_memory.exe")
  set_tests_properties(test_memory PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_memory "C:/Users/mreit/src/leaves/RelWithDebInfo/test_memory.exe")
  set_tests_properties(test_memory PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_memory NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_memstore "C:/Users/mreit/src/leaves/Debug/test_memstore.exe")
  set_tests_properties(test_memstore PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_memstore "C:/Users/mreit/src/leaves/Release/test_memstore.exe")
  set_tests_properties(test_memstore PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_memstore "C:/Users/mreit/src/leaves/MinSizeRel/test_memstore.exe")
  set_tests_properties(test_memstore PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_memstore "C:/Users/mreit/src/leaves/RelWithDebInfo/test_memstore.exe")
  set_tests_properties(test_memstore PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_memstore NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_bits "C:/Users/mreit/src/leaves/Debug/test_bits.exe")
  set_tests_properties(test_bits PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_bits "C:/Users/mreit/src/leaves/Release/test_bits.exe")
  set_tests_properties(test_bits PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_bits "C:/Users/mreit/src/leaves/MinSizeRel/test_bits.exe")
  set_tests_properties(test_bits PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_bits "C:/Users/mreit/src/leaves/RelWithDebInfo/test_bits.exe")
  set_tests_properties(test_bits PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_bits NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_cursor "C:/Users/mreit/src/leaves/Debug/test_cursor.exe")
  set_tests_properties(test_cursor PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_cursor "C:/Users/mreit/src/leaves/Release/test_cursor.exe")
  set_tests_properties(test_cursor PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_cursor "C:/Users/mreit/src/leaves/MinSizeRel/test_cursor.exe")
  set_tests_properties(test_cursor PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_cursor "C:/Users/mreit/src/leaves/RelWithDebInfo/test_cursor.exe")
  set_tests_properties(test_cursor PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_cursor NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_node "C:/Users/mreit/src/leaves/Debug/test_node.exe")
  set_tests_properties(test_node PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_node "C:/Users/mreit/src/leaves/Release/test_node.exe")
  set_tests_properties(test_node PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_node "C:/Users/mreit/src/leaves/MinSizeRel/test_node.exe")
  set_tests_properties(test_node PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_node "C:/Users/mreit/src/leaves/RelWithDebInfo/test_node.exe")
  set_tests_properties(test_node PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_node NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_db "C:/Users/mreit/src/leaves/Debug/test_db.exe")
  set_tests_properties(test_db PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_db "C:/Users/mreit/src/leaves/Release/test_db.exe")
  set_tests_properties(test_db PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_db "C:/Users/mreit/src/leaves/MinSizeRel/test_db.exe")
  set_tests_properties(test_db PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_db "C:/Users/mreit/src/leaves/RelWithDebInfo/test_db.exe")
  set_tests_properties(test_db PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_db NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_wal "C:/Users/mreit/src/leaves/Debug/test_wal.exe")
  set_tests_properties(test_wal PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_wal "C:/Users/mreit/src/leaves/Release/test_wal.exe")
  set_tests_properties(test_wal PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_wal "C:/Users/mreit/src/leaves/MinSizeRel/test_wal.exe")
  set_tests_properties(test_wal PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_wal "C:/Users/mreit/src/leaves/RelWithDebInfo/test_wal.exe")
  set_tests_properties(test_wal PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_wal NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_bigmemory "C:/Users/mreit/src/leaves/Debug/test_bigmemory.exe")
  set_tests_properties(test_bigmemory PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_bigmemory "C:/Users/mreit/src/leaves/Release/test_bigmemory.exe")
  set_tests_properties(test_bigmemory PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_bigmemory "C:/Users/mreit/src/leaves/MinSizeRel/test_bigmemory.exe")
  set_tests_properties(test_bigmemory PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_bigmemory "C:/Users/mreit/src/leaves/RelWithDebInfo/test_bigmemory.exe")
  set_tests_properties(test_bigmemory PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_bigmemory NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_map_storage "C:/Users/mreit/src/leaves/Debug/test_map_storage.exe")
  set_tests_properties(test_map_storage PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_map_storage "C:/Users/mreit/src/leaves/Release/test_map_storage.exe")
  set_tests_properties(test_map_storage PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_map_storage "C:/Users/mreit/src/leaves/MinSizeRel/test_map_storage.exe")
  set_tests_properties(test_map_storage PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_map_storage "C:/Users/mreit/src/leaves/RelWithDebInfo/test_map_storage.exe")
  set_tests_properties(test_map_storage PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_map_storage NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_file_storage "C:/Users/mreit/src/leaves/Debug/test_file_storage.exe")
  set_tests_properties(test_file_storage PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_file_storage "C:/Users/mreit/src/leaves/Release/test_file_storage.exe")
  set_tests_properties(test_file_storage PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_file_storage "C:/Users/mreit/src/leaves/MinSizeRel/test_file_storage.exe")
  set_tests_properties(test_file_storage PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_file_storage "C:/Users/mreit/src/leaves/RelWithDebInfo/test_file_storage.exe")
  set_tests_properties(test_file_storage PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_file_storage NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_string_insert "C:/Users/mreit/src/leaves/Debug/test_string_insert.exe")
  set_tests_properties(test_string_insert PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_string_insert "C:/Users/mreit/src/leaves/Release/test_string_insert.exe")
  set_tests_properties(test_string_insert PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_string_insert "C:/Users/mreit/src/leaves/MinSizeRel/test_string_insert.exe")
  set_tests_properties(test_string_insert PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_string_insert "C:/Users/mreit/src/leaves/RelWithDebInfo/test_string_insert.exe")
  set_tests_properties(test_string_insert PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_string_insert NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_merger "C:/Users/mreit/src/leaves/Debug/test_merger.exe")
  set_tests_properties(test_merger PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_merger "C:/Users/mreit/src/leaves/Release/test_merger.exe")
  set_tests_properties(test_merger PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_merger "C:/Users/mreit/src/leaves/MinSizeRel/test_merger.exe")
  set_tests_properties(test_merger PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_merger "C:/Users/mreit/src/leaves/RelWithDebInfo/test_merger.exe")
  set_tests_properties(test_merger PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_merger NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_hash_updater "C:/Users/mreit/src/leaves/Debug/test_hash_updater.exe")
  set_tests_properties(test_hash_updater PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_hash_updater "C:/Users/mreit/src/leaves/Release/test_hash_updater.exe")
  set_tests_properties(test_hash_updater PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_hash_updater "C:/Users/mreit/src/leaves/MinSizeRel/test_hash_updater.exe")
  set_tests_properties(test_hash_updater PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_hash_updater "C:/Users/mreit/src/leaves/RelWithDebInfo/test_hash_updater.exe")
  set_tests_properties(test_hash_updater PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_hash_updater NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_hash_lookup "C:/Users/mreit/src/leaves/Debug/test_hash_lookup.exe")
  set_tests_properties(test_hash_lookup PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_hash_lookup "C:/Users/mreit/src/leaves/Release/test_hash_lookup.exe")
  set_tests_properties(test_hash_lookup PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_hash_lookup "C:/Users/mreit/src/leaves/MinSizeRel/test_hash_lookup.exe")
  set_tests_properties(test_hash_lookup PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_hash_lookup "C:/Users/mreit/src/leaves/RelWithDebInfo/test_hash_lookup.exe")
  set_tests_properties(test_hash_lookup PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_hash_lookup NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_serial "C:/Users/mreit/src/leaves/Debug/test_serial.exe")
  set_tests_properties(test_serial PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_serial "C:/Users/mreit/src/leaves/Release/test_serial.exe")
  set_tests_properties(test_serial PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_serial "C:/Users/mreit/src/leaves/MinSizeRel/test_serial.exe")
  set_tests_properties(test_serial PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_serial "C:/Users/mreit/src/leaves/RelWithDebInfo/test_serial.exe")
  set_tests_properties(test_serial PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_serial NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_twoquecache "C:/Users/mreit/src/leaves/Debug/test_twoquecache.exe")
  set_tests_properties(test_twoquecache PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_twoquecache "C:/Users/mreit/src/leaves/Release/test_twoquecache.exe")
  set_tests_properties(test_twoquecache PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_twoquecache "C:/Users/mreit/src/leaves/MinSizeRel/test_twoquecache.exe")
  set_tests_properties(test_twoquecache PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_twoquecache "C:/Users/mreit/src/leaves/RelWithDebInfo/test_twoquecache.exe")
  set_tests_properties(test_twoquecache PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_twoquecache NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_aspect "C:/Users/mreit/src/leaves/Debug/test_aspect.exe")
  set_tests_properties(test_aspect PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_aspect "C:/Users/mreit/src/leaves/Release/test_aspect.exe")
  set_tests_properties(test_aspect PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_aspect "C:/Users/mreit/src/leaves/MinSizeRel/test_aspect.exe")
  set_tests_properties(test_aspect PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_aspect "C:/Users/mreit/src/leaves/RelWithDebInfo/test_aspect.exe")
  set_tests_properties(test_aspect PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_aspect NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_metrics_aspects "C:/Users/mreit/src/leaves/Debug/test_metrics_aspects.exe")
  set_tests_properties(test_metrics_aspects PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_metrics_aspects "C:/Users/mreit/src/leaves/Release/test_metrics_aspects.exe")
  set_tests_properties(test_metrics_aspects PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_metrics_aspects "C:/Users/mreit/src/leaves/MinSizeRel/test_metrics_aspects.exe")
  set_tests_properties(test_metrics_aspects PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_metrics_aspects "C:/Users/mreit/src/leaves/RelWithDebInfo/test_metrics_aspects.exe")
  set_tests_properties(test_metrics_aspects PROPERTIES  LABELS "native;unit" TIMEOUT "30" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;492;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_metrics_aspects NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_transfer "C:/Users/mreit/src/leaves/Debug/test_transfer.exe")
  set_tests_properties(test_transfer PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_transfer "C:/Users/mreit/src/leaves/Release/test_transfer.exe")
  set_tests_properties(test_transfer PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_transfer "C:/Users/mreit/src/leaves/MinSizeRel/test_transfer.exe")
  set_tests_properties(test_transfer PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_transfer "C:/Users/mreit/src/leaves/RelWithDebInfo/test_transfer.exe")
  set_tests_properties(test_transfer PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_transfer NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_replication_fsm "C:/Users/mreit/src/leaves/Debug/test_replication_fsm.exe")
  set_tests_properties(test_replication_fsm PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_replication_fsm "C:/Users/mreit/src/leaves/Release/test_replication_fsm.exe")
  set_tests_properties(test_replication_fsm PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_replication_fsm "C:/Users/mreit/src/leaves/MinSizeRel/test_replication_fsm.exe")
  set_tests_properties(test_replication_fsm PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_replication_fsm "C:/Users/mreit/src/leaves/RelWithDebInfo/test_replication_fsm.exe")
  set_tests_properties(test_replication_fsm PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_replication_fsm NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_replication_api "C:/Users/mreit/src/leaves/Debug/test_replication_api.exe")
  set_tests_properties(test_replication_api PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_replication_api "C:/Users/mreit/src/leaves/Release/test_replication_api.exe")
  set_tests_properties(test_replication_api PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_replication_api "C:/Users/mreit/src/leaves/MinSizeRel/test_replication_api.exe")
  set_tests_properties(test_replication_api PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_replication_api "C:/Users/mreit/src/leaves/RelWithDebInfo/test_replication_api.exe")
  set_tests_properties(test_replication_api PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_replication_api NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_tributary "C:/Users/mreit/src/leaves/Debug/test_tributary.exe")
  set_tests_properties(test_tributary PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_tributary "C:/Users/mreit/src/leaves/Release/test_tributary.exe")
  set_tests_properties(test_tributary PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_tributary "C:/Users/mreit/src/leaves/MinSizeRel/test_tributary.exe")
  set_tests_properties(test_tributary PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_tributary "C:/Users/mreit/src/leaves/RelWithDebInfo/test_tributary.exe")
  set_tests_properties(test_tributary PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_tributary NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_executor "C:/Users/mreit/src/leaves/Debug/test_executor.exe")
  set_tests_properties(test_executor PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_executor "C:/Users/mreit/src/leaves/Release/test_executor.exe")
  set_tests_properties(test_executor PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_executor "C:/Users/mreit/src/leaves/MinSizeRel/test_executor.exe")
  set_tests_properties(test_executor PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_executor "C:/Users/mreit/src/leaves/RelWithDebInfo/test_executor.exe")
  set_tests_properties(test_executor PROPERTIES  LABELS "native;integration" TIMEOUT "60" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;501;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_executor NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_multithread "C:/Users/mreit/src/leaves/Debug/test_multithread.exe")
  set_tests_properties(test_multithread PROPERTIES  LABELS "native;stress;concurrency" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;503;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_multithread "C:/Users/mreit/src/leaves/Release/test_multithread.exe")
  set_tests_properties(test_multithread PROPERTIES  LABELS "native;stress;concurrency" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;503;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_multithread "C:/Users/mreit/src/leaves/MinSizeRel/test_multithread.exe")
  set_tests_properties(test_multithread PROPERTIES  LABELS "native;stress;concurrency" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;503;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_multithread "C:/Users/mreit/src/leaves/RelWithDebInfo/test_multithread.exe")
  set_tests_properties(test_multithread PROPERTIES  LABELS "native;stress;concurrency" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;503;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_multithread NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_multiprocess "C:/Users/mreit/src/leaves/Debug/test_multiprocess.exe")
  set_tests_properties(test_multiprocess PROPERTIES  LABELS "native;stress;multiprocess" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;504;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_multiprocess "C:/Users/mreit/src/leaves/Release/test_multiprocess.exe")
  set_tests_properties(test_multiprocess PROPERTIES  LABELS "native;stress;multiprocess" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;504;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_multiprocess "C:/Users/mreit/src/leaves/MinSizeRel/test_multiprocess.exe")
  set_tests_properties(test_multiprocess PROPERTIES  LABELS "native;stress;multiprocess" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;504;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_multiprocess "C:/Users/mreit/src/leaves/RelWithDebInfo/test_multiprocess.exe")
  set_tests_properties(test_multiprocess PROPERTIES  LABELS "native;stress;multiprocess" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;504;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_multiprocess NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_replication_multiclient "C:/Users/mreit/src/leaves/Debug/test_replication_multiclient.exe")
  set_tests_properties(test_replication_multiclient PROPERTIES  LABELS "native;integration;network" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;505;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_replication_multiclient "C:/Users/mreit/src/leaves/Release/test_replication_multiclient.exe")
  set_tests_properties(test_replication_multiclient PROPERTIES  LABELS "native;integration;network" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;505;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_replication_multiclient "C:/Users/mreit/src/leaves/MinSizeRel/test_replication_multiclient.exe")
  set_tests_properties(test_replication_multiclient PROPERTIES  LABELS "native;integration;network" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;505;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_replication_multiclient "C:/Users/mreit/src/leaves/RelWithDebInfo/test_replication_multiclient.exe")
  set_tests_properties(test_replication_multiclient PROPERTIES  LABELS "native;integration;network" TIMEOUT "120" WORKING_DIRECTORY "C:/Users/mreit/src/leaves" _BACKTRACE_TRIPLES "C:/Users/mreit/src/leaves/CMakeLists.txt;320;add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;505;leaves_add_test;C:/Users/mreit/src/leaves/CMakeLists.txt;0;")
else()
  add_test(test_replication_multiclient NOT_AVAILABLE)
endif()
subdirs("BLAKE3/c")
subdirs("leveldb/third_party/benchmark")
subdirs("leveldb")
